version: "3.1"

services:
  # user-db:
  #   container_name: user-db
  #   image: prismagraphql/mongo-single-replica:4.4.3-bionic
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: prisma
  #     MONGO_REPLICA_HOST: user-db
  #     MONGO_REPLICA_PORT: 27017
  #   ports:
  #     - 27017:27017

  # movie-db:
  #   container_name: movie-db
  #   image: prismagraphql/mongo-single-replica:4.4.3-bionic
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: prisma
  #     MONGO_REPLICA_HOST: movie-db
  #     MONGO_REPLICA_PORT: 27018
  #   ports:
  #     - 27018:27018

  # rate-db:
  #   container_name: rate-db
  #   image: prismagraphql/mongo-single-replica:4.4.3-bionic
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: prisma
  #     MONGO_REPLICA_HOST: rate-db
  #     MONGO_REPLICA_PORT: 27019
  #   ports:
  #     - 27019:27019

  gw-service:
    container_name: gw-service
    build:
      context: ./gateway
      dockerfile: Dockerfile
    depends_on:
      - users-service
      - movies-service
      - rates-service
    restart: on-failure
    ports:
      - 3000:3000

  users-service:
    container_name: users-service
    env_file: ./users-application/.env
    build:
      context: ./users-application
      dockerfile: Dockerfile
    # depends_on:
    #   - user-db
    ports:
      - 3001:3001
    # links:
    #   - "user-db"

  movies-service:
    container_name: movies-service
    env_file: ./movies-application/.env
    build:
      context: ./movies-application
      dockerfile: Dockerfile
    # depends_on:
    #   - movie-db
    ports:
      - 3002:3002
    # links:
    #   - "movie-db"

  rates-service:
    container_name: rates-service
    env_file: ./rates-application/.env
    build:
      context: ./rates-application
      dockerfile: Dockerfile
    # depends_on:
    #   - rate-db
    ports:
      - 3003:3003
    # links:
    #   - "rate-db"
